googleapis/nodejs-common

.circleci/config.yml
package.json

Releasing v0.15.0 from this new repository (moved from GoogleCloudPlatform).

release v0.15.0

---

README.md

Auto-generated `README.md` contained some links and stuff not applicable to common package.

docs: fix-common-readme

---

package.json

We need to make a patch release to fix the log-driver dependency issue (#33, #16).

release 0.16.1

---

src/logger.js
src/operation.js
src/paginator.js
src/service-object.js
src/service.js
src/util.js
test/index.js
test/logger.js
test/operation.js
test/paginator.js
test/service-object.js
test/service.js
test/util.js

Just switches from var over let and const.

chore: switch to let/const

---

package.json

This release contains only dependency updates and some style fixes.
- (#16) Dependencies with licensing problems
- (#54) Switch to `let`/`const`
---

chore: release 0.16.2

---

src/util.js
test/util.js

Create MissingProjectId error class

---

.gitignore
src/operation.ts
src/paginator.ts
src/service-object.ts
src/service.ts
src/util.ts
test/index.ts
test/logger.ts
test/operation.ts
test/paginator.ts
test/service-object.ts
test/service.ts
test/util.ts

Fairly routine find & replace to catch most of the places where we can use arrow functions.  Not done yet, but a good start. Rubber stamp appreciated :)

chore: use arrow functions

---

package.json

fix: ensure packaging works

---

package.json
src/logger.ts
src/operation.ts
src/paginator.ts
src/service-object.ts
src/service.ts
src/util.ts

Not complete at all, but a good start towards typing

chore: types, types, types

---

package.json
src/index.ts
src/paginator.ts
test/paginator.ts

chore: es6ify paginator.ts

---

src/index.ts
src/operation.ts
src/service-object.ts
test/operation.ts
test/service-object.ts

chore: upgrade service-object.ts to es6

---

package.json
src/index.ts
src/operation.ts
src/service-object.ts
test/operation.ts
test/service-object.ts

chore: convert operation.ts to es6

---

src/index.ts
src/paginator.ts
src/service-object.ts
src/service.ts
src/util.ts
test/operation.ts
test/paginator.ts
test/service-object.ts
test/service.ts
test/util.ts

feat: convert util.ts to es6

---

src/paginator.ts
src/util.ts

fix: add explicit typing to please the compiler

---

src/util.ts
test/util.ts

gts checking, one file at a time to freedom.

chore: gts check for util.ts

---

package.json
src/service-object.ts
src/service.ts
src/util.ts
test/service-object.ts
test/service.ts
test/util.ts

chore: enable gts

---

package.json

🚢🚂Release notes drafted here:
https://github.com/googleapis/nodejs-common/releases/edit/untagged-5a0a1f66bf8cbda3b11e
Resolves #116 
FYI @googleapis/node-team

chore: release 0.18.0

---

.circleci/config.yml
package.json

🙄 [release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-8b20c1ce813ca3a3d76b)

chore: release 0.18.2

---

package.json

fix: include request and duplexify types

---

src/index.ts
src/service-object.ts
src/util.ts
test/service-object.ts

fix: back-compat issues with cloud-profiler

---

src/service.ts
test/service.ts

These came up while upgrading a few other modules.

fix: back-compat for service.ts

---

package.json

[Release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-7ee9c3835bef05d74cf7)

chore: release 0.18.4

---

src/service-object.ts
src/service.ts
src/util.ts
test/service-object.ts

Found a few more broken APIs when updating other packages.

fix: repair requestStream and other back-compat changes

---

src/service.ts
src/util.ts
test/service.ts
test/util.ts

I think? this resolves #131.  @kjin would you mind taking this branch for a spin?

fix: repair makeAuthenticatedRequest callback order

---

package.json

[release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-95b53230ab3869ab53cd)

chore: release 0.18.5

---

src/service-object.ts
src/service.ts
test/service-object.ts
test/service.ts

fix: swap resp and body in request callback

---

package.json

[release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-4303975ba4d88eedb55b)

chore: release 0.18.6

---

package.json

[Release Notes](https://github.com/googleapis/nodejs-common/releases/tag/untagged-dd05f02144eb39e78a62)

chore: release 0.18.7

---

package.json

[Release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-65d3796f7aa117addc34)

chore: release 0.18.8

---

src/service.ts

This broke as part of the great TypeScript migration, and is breaking system tests across the land.

fix: pass responses in errors with request callbacks

---

src/util.ts
test/util.ts

Fixes #151
~Appropriate docs were updated (if necessary)~

Set the PartialFailureError name to 'PartialFailureError'.

---

package.json

[Release Notes](https://github.com/googleapis/nodejs-common/releases/tag/untagged-df9975ca194316f7f3b1)

chore: 0.19.0 release proposal

---

package.json

[release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-a1de70bbb514c10606e4)

chore: release 0.19.1

---

package.json

[Release Notes](https://github.com/googleapis/nodejs-common/releases/tag/untagged-8c2420a5e179441d1b48)

chore: 0.19.2 release proposal

---

package.json

[release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-184b4bda556fa496a876)

chore: release 20.0.0

---

src/service-object.ts

This came up when trying to upgrade the nodejs debug agent to use 0.20.0 :)

fix: loosen index type for service-object

---

package.json

[release notes!!!!!1](https://github.com/googleapis/nodejs-common/releases/edit/untagged-53033fe409333db6f978)

chore: release 0.20.1

---

test/service-object.ts

fix: UnhandledPromiseRejection in ServiceObject test

---

src/operation.ts
src/paginator.ts
src/service-object.ts
src/service.ts
src/util.ts
test/index.ts
test/install.ts
test/logger.ts
test/operation.ts
test/paginator.ts
test/service-object.ts
test/service.ts
test/util.ts
tsconfig.json

Fixes #185, and you know, all the other upstream modules I broke with 0.20.2.  Synthetic imports offer us very little gain, and lots of pain.

fix: no synthetic imports

---

package.json

TBR = @ofrobots (this is busted in prod)

chore: release 0.20.3

---

CHANGELOG.md
package.json

Release nodejs-common v0.21.1

---

test/install.ts

fix: increase timeout for install test

---

src/util.ts
test/util.ts

Fixes https://github.com/googleapis/nodejs-bigquery/issues/171

Remove old code & replace project ID token in multipart arrays.

---

CHANGELOG.md
package.json

Release nodejs-common v0.22.0

---

CHANGELOG.md
package.json

Release nodejs-common v0.23.0

---

src/service-object.ts
src/service.ts

These came up while trying to convert a library to TypeScript.

fix: fix the types

---

CHANGELOG.md
package.json

Release nodejs-common v0.24.0

---

src/index.ts
src/service-object.ts
test/service-object.ts

Downstream TypeScripted repos *might* have to update types.

Improve types for SO.getMetadata, setMetadata

---

src/service-object.ts
test/service-object.ts

Improve TypeScript types for async operations

---

CHANGELOG.md

Fix link to this repo's npm package site in CHANGELOG.md

---

test/service.ts

To get coverage up above 95% in that file ...
- [x ] Tests and linter pass
- [x ] Code coverage does not decrease (if any source code was changed)
- [x ] Appropriate docs were updated (if necessary)

Add unit tests for service.ts

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.25.1

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.25.2

---

src/index.ts
src/service-object.ts

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

fix(types): improve TypeScript types

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.25.3

---

package.json
system-test/fixtures/kitchen/package.json

*WARN*: require typescript >=3.1.0

chore(deps): upgrade @google-cloud/projectify to ^0.3.1

---

CHANGELOG.md
package.json
samples/package.json

feat: release @google-cloud/common v0.26.1

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.27.0

---

src/util.ts
test/service.ts
test/util.ts

We use this pattern all over the place, and it would be good to have a single tested implementation :)

feat: add maybeOptionsOrCallback util method

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.28.0

---

src/index.ts
src/service-object.ts
src/service.ts
src/util.ts
test/service-object.ts
test/service.ts

This reverts commit a732f8dfbcf8aa68c8d04ef89890d166506baa20.

fix: Revert "fix: reverse order of request callback params (#335)"

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.29.0

---

src/service.ts

fix: bind to this instead of true

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.29.1

---

package.json
src/service-object.ts
test/operation.ts
test/service-object.ts

fix: inherit requestModule from parent

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.30.0

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.30.1

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.30.2

---

src/util.ts
test/util.ts

Fixes https://github.com/googleapis/nodejs-storage/issues/27

fix: remove timeout rule from streaming uploads

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.31.0

---

src/service-object.ts
test/service-object.ts

Fixes https://github.com/googleapis/nodejs-bigquery/issues/362

fix(autoCreate): leave user options intact

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.31.1

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.32.0

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/common v0.32.1

---

src/service-object.ts
src/service.ts

docs: remove @private modifier from request methods

---

package.json
src/service-object.ts
src/service.ts
src/util.ts
test/operation.ts
test/service-object.ts
test/service.ts
test/util.ts

fix(deps): update to the latest version of teeny-request

---

package.json

see: https://github.com/googleapis/teeny-request/pull/75

fix(deps): teeny-request@5.2.0 with fixes for http

---

package.json

see: https://github.com/googleapis/nodejs-speech/issues/243

fix(deps): force newer auth library with various fixes

---

src/operation.ts
src/service-object.ts
test/operation.ts

Allow the poll interval for long running operations to be configured.

feat: allow poll interval to be configured

---

src/util.ts
test/util.ts

Towards googleapis/nodejs-storage/issues/956 as a prerequisite to googleapis/nodejs-storage/pull/1074
to provide the same functionality as [gcs-resumable-upload](https://github.com/googleapis/gcs-resumable-upload/pull/135)

feat: add progress events

---

src/util.ts
test/util.ts

Closes #562
RE: https://github.com/googleapis/nodejs-storage/issues/833
This will add retries for the 408 error. Previously approved in #562, just needed a test.

fix: retry error code 408

---

src/service.ts
test/service.ts

This will allow us to get all of the user-defined request interceptors, which is required when we need to make an API request outside of the nodejs-common "request()" method.

feat: expose method to get request interceptors
