googleapis/nodejs-common

- .circleci/config.yml
Common package does not have any system tests or samples so we don't need to have those sections in circleci config.
> no system tests and sample tests for common

- js-green-licenses.json
- package.json
The package, `log-driver`, should be whitelisted. See
https://github.com/googleapis/nodejs-common/issues/16.
> chore: license check in posttest

- src/paginator.js
- src/util.js
- test/paginator.js
- test/util.js
Fixes #24
This will allow all paginated streaming methods in the various `@google-cloud/*` libraries to customize the stream options, most popularly "highWaterMark" (used to control backpressure).
> Support Stream constructor options in pagination methods.

- package.json
The first time this year where greenkeeper CI check proved useful.
> fix: pin log-driver to 1.2.5

- src/util.js
- test/util.js
Fixes #31 
This will block google-auto-auth from receiving `{{projectId}}`, which it assumes is the user's project ID.
> Do not allow the project ID token to be sent to google-auto-auth.

- package.json
- src/service-object.js
Looks like the latest prettier update introduced incompatibility. Fixing the code formatting to make prettier happy, and updating the required version in `package.json`.
> style: fix prettier incompatibility

- .appveyor.yml
We don't run it on node4, 6, 7 for other libraries, no reason to do it in this library as well.
> chore: run appveyor on node8 only

- js-green-licenses.json
`log-driver` has no license issues anymore.
> chore: delete js-green-licenses.json

- src/service.js
- test/service.js
Fixes #11 
This will allow a user to provide an access token, which will then be used by google-auto-auth.
> Support access token

- package.json
- src/util.ts
I ain't no expert in nodejs streams. But at a glance, it didn't look like we really needed `through2` in the mix here.  What do y'all think?  Does this PR pretty much do what through2 was doing for us?
> chore: remove through2

- package.json
- src/paginator.ts
- test/paginator.ts
I'm just playing around with reducing our dependency graph.  I think I covered most of the useful stuff concat-stream was doing 🤷‍♂️ 
@stephenplusplus - do you know what kind of data these streams typically handle?  The tests just send through buffers, but it looks like concat-stream does a fair bit with type checking.  It would be super rad to know what exactly this does to make sure I ain't breaking it ⚒
> chore: remove concat-stream

- .circleci/config.yml
- package.json
So it looks like I messed up.  I published 0.18.0, which contains no source files.  Turns out it's because we never call `npm install` to actually kick off the build and such.  I am a little surprised the `prepare` npm script didn't fail, but 🤷‍♂️ 
This ought to fix it.  Release notes:
https://github.com/googleapis/nodejs-common/releases/edit/untagged-23dca0d5aa9dfd561c59
> chore: release 0.18.1

- package.json
A few bug fixes to unblock cloud-profiler-nodejs.  Release notes drafted here:
https://github.com/googleapis/nodejs-common/releases/edit/untagged-e5260db02fbe02a2993f
> chore: release 0.18.3

- src/index.ts
- src/logger-compat.ts
- src/logger.ts
- test/logger.ts
This PR changes `LoggerOptions` to `LoggerConfig` and exposes it. `ServiceConfig` is exposed as well. This allows us to obtain the types need to construct these objects.
> fix: expose LoggerConfig and ServiceConfig

- src/index.ts
- src/logger-compat.ts
- src/logger.ts
- test/logger.ts
__edit:__ _In addition to the below, this PR removes `levels` from the documented API of `LoggerConfig`. There are no behavioral changes here, and impact should overall be minimal because `LoggerConfig` (along with `Logger`) was introduced in 0.18._
This change makes it so that object of type `Logger` by default expose log levels corresponding to the default options. This is the primary use case for objects of type `Logger`.
For `Logger` objects with custom log levels:
```ts
const l = new Logger() as CustomLevelsLogger;
l.baby('foo');
```
This makes mocking `Logger` objects easier, and also gives us code completion for default log levels.
> feat: remove `levels` from LoggerConfig and don't expose index property on Logger

- src/util.ts
- test/util.ts
Currently `promisifyAll` doesn't support es classes, where the methods are added in the class declaration:
```js
class MyClass {
thisShouldBePromisified() {
// but it currently isn't :(
}
}
util.promisifyAll(MyClass);
// Uncaught TypeError: Cannot read property 'then' of undefined
new MyClass().thisShouldBePromisified().then(console.log)
```
Now here's where testing gets fun. The ts compiler will convert a class to whatever node version target, in this case v4, which means that we can't just create a class to test this on. In order to get around this we need to use `eval` to create a real es class that won't get transpiled.
Following this thought, you may think creating a `.js` file with the same code would suffice, **however**, since the tests also run on node v4, it would cause a syntax …
> Add promisifyAll support for es classes

- package.json
- src/logger-compat.ts
TypeScript 2.9 just came out. This upgrades the TSC version and also locks it at 2.9.
> chore: upgrade and lock typescript at 2.9

- .circleci/config.yml
`npm publish` did not work when run as root. Let's run as user `node` as we do in all other projects.
> chore: run CI as non-root user

- src/logger-compat.ts
- src/logger.ts
This change just puts `LEVELS` as a static field on the `Logger` object.
> feat: expose Logger.LEVELS

- package.json
- src/util.ts
This fixes a hard-to-explain break in the system tests in nodejs-storage 🤷‍♂️ Blocking https://github.com/googleapis/nodejs-storage/pull/202
Resolves #137
> fix: use through() again

- src/service-object.ts
> fix: loosens metadata type to any in ServiceObject

- package.json
[release notes](https://github.com/googleapis/nodejs-common/releases/edit/untagged-7a301c737c1937ecf0c4#)
----------
This is a patch release that contains several bug fixes, updated dependencies, and tool fixes. 
a7c763a fix: callback request with body and response (#182)
9146ec4 fix: ServiceObject: loosen metadata type (#181)
5921721 fix: UnhandledPromiseRejection in ServiceObject test (#175)
f59f537 fix(deps): update dependency retry-request to v4 (#179)
5b4132f chore(deps): update dependency sinon to v6 (#178)
272d3be chore(deps): update dependency gts to ^0.7.0 (#177)
a36ee6a test: test the typescript install (#183)
f2de3e9 Configure Renovate (#170)
a35bd97 refactor: drop repo-tool as an exec wrapper (#173)
620844d fix: update linking for samples (#171)
> chore: release 0.20.2

- src/index.ts
- src/service-object.ts
- src/service.ts
This way `service` does not import `service-object`, only the
other way round.
> refactor: remove circular imports

- package.json
- src/util.ts
- test/util.ts
BREAKING CHANGE: This change removes the following methods from the `util` class:
- `util.replaceProjectIdToken`
- `util.extendGlobalConfig`
- `util.normalizeArguments`
- `util.createLimiter`
- `util.privatize`
These methods have either been replaced with smaller single purpose modules, or are no longer necessary. 
Side note: deleting code is fun, and feels really good.
> chore: remove dead code and packages

- package.json
- src/service-object.ts
- src/service.ts
- src/util.ts
- test/fixtures/kitchen/src/index.ts
- test/operation.ts
- test/service-object.ts
- test/util.ts
`Service`, `ServiceObject`, and `util.makeRequest()` must be
initialized with an HTTP dependency, e.g., `request`.
The second parameter of `util.makeRequest`, a configuration
object, is mandatory.
Ultimately, this change will improve startup time for the
client libraries. Before this change, `nodejs-common` required
`request` as HTTP dependency, which is a very large dependency. By making the
HTTP dependency configurable, client libraries can use
smaller dependencies instead of `request`. Thus reducing startup time.
For an end-to-end integration, see https://github.com/googleapis/nodejs-translate/pull/98.
> feat: make HTTP dependency configurable

- src/util.ts
`options.request` is already initialized with the default values.
> fix: set default once

- src/service.ts
- test/service.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> fix(service): use getProjectId instead of getDefaultProjectId

- package.json
- src/service-object.ts
- src/service.ts
- src/util.ts
All of these replacements are synonymous with `is`'s implementations -- all of `is`'s tests pass using these versions.
Closes #163
> Remove 'is' dependency

- src/util.ts
- system-test/fixtures/kitchen/src/index.ts
- test/util.ts
Fixes https://github.com/googleapis/nodejs-storage/issues/27
Fixes https://github.com/googleapis/nodejs-storage/issues/312
Previously, we were retrying streaming POST requests, in places like `file.createWriteStream()`. That's not actually possible, since once the data has left the user's stream, and we pass it to the upstream API, it's effectively gone to free up memory. So if suddenly the API decides it's upset, we can't rewind the state of the transfer.
> fix: Do not retry streaming POST requests.

- CHANGELOG.md
- package.json
- samples/package.json
Making this a patch release so that the nodejs-projectify fix would go out to common's dependents.
> feat: release @google-cloud/common v0.26.2

- src/index.ts
- src/operation.ts
- src/service-object.ts
- src/service.ts
- src/util.ts
- system-test/fixtures/kitchen/src/index.ts
- test/service-object.ts
- test/service.ts
When I converted nodejs-common to TypeScript, I made the mistake of trying to make `request` and `request_` async functions.  While we were able to fix *most* of the issues this caused, it had some unexpected results in nodejs-compute, where system tests have been broken for months.  Going back to callbacks should fix this.
Resolves #172
> fix: revert async behavior of request

- src/index.ts
- src/service-object.ts
- src/service.ts
- src/util.ts
- test/service-object.ts
- test/service.ts
Hilariously the order of types for the request callback have been wrong for some time.  This change just flips the order of the types, and should have no actual runtime impact.
> fix: reverse order of request callback params

- package.json
This updates google-auth-library to 3.0, which replaced axios with gaxios. More info in the 3.0 release notes: https://github.com/googleapis/google-auth-library-nodejs/releases/tag/v3.0.0
> chore(deps): update dependency google-auth-library to v3.0.0

- src/operation.ts
- src/service-object.ts
- test/service-object.ts
This allows `options` to be passed to several methods on ServiceObject:
For Storage, in order to support the `userProject` object, we ended up duplicating many of these methods, so that we could pass extra parameters along with the request as query string parameters. With this change, we will just support that here, where it probably belongs.
Sending this in early for feedback before I carry on with the other methods and tests.
> feat: allow options to ServiceObject methods

- test/service-object.ts
This was accidentally left off of my last PR, #349.
> test: add tests for ServiceObject methods that accept options

- src/service-object.ts
- test/service-object.ts
When you instantiate a ServiceObject, you can provide some default request configuration options that will be sent along with every API request. This is popular in Storage, where, for example, if the user passes a "generation" for a File object, we put it in the query string parameters that go out with every HTTP request.
We just landed new behavior in this library where the ServiceObject methods, like `get()`, `getMetadata()`, etc. allow an options object. That object is treated as the query string parameters for that request.
And now, we have a new problem I didn't notice until now! Okay, two:
1) we need to deeply extend the default request options with the new, user request options, and
2) the options set at the time of the method call should take precedence over the default ones we …
> fix: favor user options over defaults

- src/service-object.ts
- test/service-object.ts
Need to clone the default request configuration object. ☺️
> fix: clone default request configuration object

- src/util.ts
- test/util.ts
Fixes https://github.com/googleapis/nodejs-bigquery/issues/326
---
Using the following server error for the before/after
```json
{
"state": "DONE",
"errorResult": {
"reason": "invalid",
"location": "",
"message": "Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details."
},
"errors": [
{
"reason": "invalid",
"location": "",
"message": "Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details."
},
{
"reason": "invalid",
"location": "",
"message": "Error while reading data, error message: JSON parsing error in row starting at position 0: Could not convert value to …
```
> refactor: change error message format to multiline

- package.json
- src/util.ts
- test/util.ts
Fixes #392.  This removes the `@types/duplexify` package entirely from the tree.  It was causing a bunch of unrelated issues with `esModuleInterop`, and has generally been a pain in the neck.  Instead, this just copies over the needed interfaces.
> fix(ts): do not ship @types/duplexify

- src/service-object.ts
- src/service.ts
- src/util.ts
- test/operation.ts
- test/service-object.ts
- test/util.ts
**BREAKING CHANGE**: This PR removes the ability to configure a custom implementation of the `Request` module. This was necessary when we were migrating from `request` to `teeny-request`, but that migration is now complete.  All interfaces at accepted a custom implementation of `request` will no longer accept one. `teeny-request` is now just included in the box.
This change is being made to simplify the `request` interface touch points.
> refactor: remove configurable request

- package.json
see: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34414 the release of `@types/node@11.13.0` breaks EventEmitter, such that it is no longer coerced as a `Function`.
This is a temporary fix to address https://github.com/googleapis/nodejs-storage/pull/649, https://github.com/googleapis/nodejs-storage/pull/655, etc., until we get feedback from DefinitelyTypes.
> fix: @types/node@11.13.0 breaks paginate/promisifyAll

- package.json
Fixes issues seen here: https://github.com/googleapis/cloud-debug-nodejs/pull/667
teeny-request is required in util.js, but is only currently present as a dev-dependency.
> fix: teeny-request should be dependency

- src/service.ts
- test/service.ts
BREAKING CHANGE: This adds the `apiEndpoint` property as a required field for the `ServiceConfig`, and makes it a public property on the `Service` class.  This is being added to broadly support `apiEndpoint` overrides.
See https://github.com/googleapis/nodejs-bigquery/pull/455 to see how this would be used.
> feat!: add apiEndpoint property to service config

- package.json
- src/service.ts
Previously, some API request failures were mistakenly being retried. For more information, please see fhinkel/teeny-request#39
> chore(deps): update HTTP transport library, teeny-request

- src/service-object.ts
Add an additional generic type `U = any` to `ServiceObject` to provide better typings for getMetadata/setMetadata methods.
Currently, inherited `getMetadata` and `setMetadata` return `metadata` object as `any` - users do not get type hints or safety on the metadata object returned by calling these methods.
Upgrading to this release will not cause breaking change because the generic type `U` is defaulted to `any` if not provided by the subclass. Packages that later override the generic type however will cause breaking change as:
1) `metadata` property of the inheriting `ServiceObject` class will be typed to the actual metadata type
2) `getMetadata` and `setMetadata` will invoke callback/ return promise that resolves to the metadata type, which is previously an `any`.
3) `setMetadata` will …
> fix(ts)!: provide optional typing for set/getMetadata

- src/util.ts
- test/util.ts
Fixes #446.
before:
File               |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------|----------|----------|----------|----------|-------------------|
All files          |    99.24 |    97.86 |      100 |    99.23 |                   |
index.ts          |      100 |      100 |      100 |      100 |                   |
operation.ts      |      100 |      100 |      100 |      100 |                   |
service-object.ts |      100 |    97.92 |      100 |      100 |               184 |
service.ts        |    98.15 |    95.24 |      100 |    98.11 |               232 |
util.ts           |    98.97 |     97.9 |      100 |    98.96 |           367,418 |
after:
File               |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s | …
> Includes the response in the error message when the response body can't be parsed as JSON.

- src/service.ts
- test/service.ts
add `timeout` to `service` and pass it to reqOpts.
With this `timeout` can be exposed to users in the child dependencies (storage, bigquery...)
Will apply to googleapis/nodejs-storage/issues/733
> feat: add timeout to options and use it in the reqOpts

- src/service.ts
`timeout` isn't necessarily (and doesn't need to be) defined, so this change removes the type coercion. This is a TS change on an internal field only.
> refactor: correct internal timeout field type

- src/util.ts
- test/util.ts
Fixes https://github.com/googleapis/google-auth-library-nodejs/issues/620
Not all API endpoints require authentication, so even when the auth library can't figure out how to generate an API token, we still want to send the API request without one. It might be totally fine.
Or, it might not be, and the API actually requires a token. Fine, then. It returns a 401 with *that API's version of a helpful error.* But, turns out, the auth library has a pretty good version of a helpful error that we'd rather use.
> feat: return more helpful error when authentication fails

- src/util.ts
- test/util.ts
Fixes #465
- automated tests may fail because of https://github.com/googleapis/teeny-request/pull/66
> fix: capture message in ApiError.stack

- src/util.ts
- test/util.ts
It seems reasonable to retry if we observe an `EAI_AGAIN` as a `reason` for an error.
fixes: #473
---
@vieira if this was in fact the cause of #473, I believe this should address it.
> feat: if we see EAI_AGAIN error for reason, retry request

- src/operation.ts
- src/service-object.ts
- src/service.ts
- test/operation.ts
- test/service-object.ts
- test/service.ts
BREAKING CHANGE: This removes support for custom promises.  When this feature was originally rolled out, promise support in node.js and the browser was somewhat inconsistent.  Today, all supported versions of nodejs enjoy a consistent, performant implementation of promises.   Explicitly removing this feature to ensure consistency.
> fix!: remove support for custom promises

- samples/quickstart.js
- samples/system-test/test.js
- src/service.ts
- test/service.ts
Supplies a way to amend the user agents used to make requests, to better track usage.
🦕
> feat(service): add optional provided user agent

- src/service-object.ts
- src/service.ts
Currently, users are unable to set their own interceptors. This change will enable:
```ts
file.interceptors.push({
request: reqOpts => {
reqOpts.timeout = 0;
return reqOpts;
}
});
```
> fix: allow users to set interceptors

- src/service-object.ts
- test/service-object.ts
- test/service.ts
Ah, the good old days of PR #589. Young, innocent @stephenplusplus thought just one method to expose the request interceptors would be enough. Until later that night, in the wee hours of the morning, he shot up instantly from his bed with a terrible shout: "What about the service objects?!"
He was right. Those lonely service object interceptors would not be accessible from the current code-- at least, not reasonably. The next day, he submitted a PR to add a new method to ServiceObject by the same name as the previous PR's addition.
This is that PR.
> feat: add ServiceObject#getRequestInterceptors()

- src/util.ts
- test/util.ts
I removed the code that throws an `ApiError` if the response body turns out to be non-JSON, a bit weary of the unintended consequences this might have to our downstream libraries. This technically shouldn't occur if the API behaves correctly, i.e. always a JSON body if code is 200-299.
> fix: allow non-JSON body
